apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-reporting-operator
        tag: latest
  metering-operator:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-helm-operator
      tag: latest
  metering-helm-operator:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-helm-operator
        tag: latest
  metering-reporting-operator:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-reporting-operator
        tag: latest
  metering-presto:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-presto
        tag: latest
  metering-hive:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-hive
        tag: latest
  metering-hadoop:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-hadoop
        tag: latest
        
