apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec: 
  reporting-operator:
    spec:
      image:
        repository: it-registry.redhat.ren:5021/openshift/origin-metering-reporting-operator
        tag: 4.1
  presto:
    spec:
      hive:
        image:
          repository: it-registry.redhat.ren:5021/openshift/origin-metering-hive
          tag: 4.1
      presto:
        image:
          repository: it-registry.redhat.ren:5021/openshift/origin-metering-presto
          tag: 4.1
  hdfs:
    spec:
      image:
        repository: it-registry.redhat.ren:5021/openshift/origin-metering-hadoop
        tag: 4.1
        
