apiVersion: v1
baseDomain: dynamic.opentlc.com
metadata:
  name: nw979
networking:
  networkType: OpenShiftSDN
  machineCIDR: 10.20.0.0/24
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    provisioningNetworkCIDR: 172.22.0.0/24
    provisioningNetworkInterface: ens3
    apiVIP: 10.20.0.110
    ingressVIP: 10.20.0.112
    dnsVIP: 10.20.0.111
    bootstrapOSImage: http://10.20.0.2/images/rhcos-45.82.202008010929-0-qemu.x86_64.qcow2.gz?sha256=c9e2698d0f3bcc48b7c66d7db901266abf27ebd7474b6719992de2d8db96995a
    clusterOSImage: http://10.20.0.2/images/rhcos-45.82.202008010929-0-openstack.x86_64.qcow2.gz?sha256=359e7c3560fdd91e64cd0d8df6a172722b10e777aef38673af6246f14838ab1a
    hosts:
      - name: master-0
        role: master
        bmc:
          address: ipmi://10.20.0.3:6203
          username: admin
          password: redhat
        bootMACAddress: de:ad:be:ef:00:40
        hardwareProfile: openstack
      - name: master-1
        role: master
        bmc:
          address: ipmi://10.20.0.3:6204
          username: admin
          password: redhat
        bootMACAddress: de:ad:be:ef:00:41
        hardwareProfile: openstack
      - name: master-2
        role: master
        bmc:
          address: ipmi://10.20.0.3:6205
          username: admin
          password: redhat
        bootMACAddress: de:ad:be:ef:00:42
        hardwareProfile: openstack
      - name: worker-0
        role: worker
        bmc:
          address: ipmi://10.20.0.3:6201
          username: admin
          password: redhat
        bootMACAddress: de:ad:be:ef:00:50
        hardwareProfile: openstack
      - name: worker-1
        role: worker
        bmc:
          address: ipmi://10.20.0.3:6202
          username: admin
          password: redhat
        bootMACAddress: de:ad:be:ef:00:51
        hardwareProfile: openstack

sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClEiiLHmmWcWmrDM3RgCgFQ4B15fP/dN7WUQVy5jBTzzBLRkWFicvhKIOXfUNYAmfsLss2wTXe9rnvcgYWmHydpo0oiHZtihs694xBbq9oBPP/+oW/PDSGHksT2YnYAdnYGJ8Qt9JiRITyko5/PFpZduuljz1nn2vjR2zow7jpMheLbz9bXipLqz+MguWq8H3ocTPXfPoASwq6D9TPm6zHestIq1Ocm8xy+PdKNSd1aHXGKUjHawdoeBUGz0cwt4VkJ3hX3WS7HzrLQa8KXLWKii3tQ5jgvS4DXyFjAoGunTvYCtbC/5xlgez1Y6IMqoRKwGnzrk2Mw/gdsah/Go2nHFTcoPx0PD4pBlsGB22fB0oqxL/BZXhexDc+qZdig4q4/8NR9VbRxp3ftBeohU9BFgkxTibZZf4etCmRC54kCvJwJY3LYohpUIs0jEy/sTq73merZbTCoyOCo/+a7FKxPDjFipAhw7nyH8LHSf5YTbllVmM3vgeL3nfxTcZcFr8= lab-user@provision'
imageContentSources:
- mirrors:
  - provision.nw979.dynamic.opentlc.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - provision.nw979.dynamic.opentlc.com:5000/ocp4/openshift4
  source: registry.svc.ci.openshift.org/ocp/release
pullSecret: '{"auths":{"quay.io":{"email":"rhpds-admins@redhat.com","auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3JocGRzYWRtaW5zcmVkaGF0Y29tMWZyZ3NpZHV6cTJkem5zajNpdzBhdG1samg3OjJMSTFEVTM1MFVCQks1ODRCTFVBODBFTTU1V0RQRDNXRDI0Qko2Q0I5VzNFSFIzS0pSSFhOSFgyVllNMlFFMVQ="},"registry.redhat.io":{"email":"rhpds-admins@redhat.com","auth":"NTE1NDg0ODB8dWhjLTFGckdzSURVWlEyRHpuU0ozaVcwQXRtTEpoNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpPR1prTVdJNFpqYzJOamcwTmpKbVlXTTRaVFpsWVRnd09EUTJOMkkzTnlKOS5YUmQ5LS1LQ3kzVlpVbF9ldTc0THpQMFEzOVYwRUVfeWRZOE5pVGRScUlyd2hVRHYtcFF2ZEtLV1ZpVmlaQWF0QkhEUVdmVDB1Z2pfTWIzYmNPUktqSXdBNldQTXYxWTc1RmhYQUg1S2Myc3lnSHVxWTRfZlhSOXJnbW42N0l0MmhiUXJyb3BBNXlaYXpXSzhPeTBJb29VWFAteDBPUjZ2VDJTVGktbm5sblBLbEFSWTBEZkxJYmk3OHZlZXFadUpyUDl4SzlXdnRaOEZOREpzQnlUc2VmeFRoVmtLMDVwVDlhTk9nTkxITGJMeU5sdEc1RE9xU1JiZ1hLMDJ6RXNaU3BwYmZLdVAwNVJYQWljQy14WEZiamtLaFpkYTgwV3lnZDJKcTZXWVF3WW83ZXgtLUh1MEpKeXBTczRINVY0Nm50dTNVRlNVUERBZEJ5VmVDU2RxckpzUWZoSmlpLVdJbXdjWnp6LUNwTlRfNVo0ei1WUkc0aV9hVF9TWnVkQzVySmFLdFpHS1RQWlg0SDlNLWxDeFlHZDJNYzhuWlc4NWVUeTJPYnBVOHA2S19sU3A3Wm15RzhEbWh6bFAtYTQzb0J1V3hJTHg3Y283U3BkOFRyYVNRbjVnaFpvc0VKZGp6X2ljTlFhVktNazFHQjEwbU1uOXJBeGdUcm5qU09aSEZvcXdmX2Y2dnZFWi0ySUp2Qk91UUZRQThsZDlzRDVDb1ZWNEdwTWx1Rl8zZGJqcXhuVTE0WXdHT2RhSldSOEtMTlFwbU9RV0JrWFJIcVpwN01UT0ZDX0dMVDRWeGNTMXhva0p6RUFxN1c4NzBSQVo4VnAtUGdscEJCc2RDT2tfdGNCNEY5T2hkZ0NPb3JMNHJkZmp6cEJobUZuMEhzVkFFNGJkaWhfRjNGSQ=="},"cloud.openshift.com":{"email":"rhpds-admins@redhat.com","auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3JocGRzYWRtaW5zcmVkaGF0Y29tMWZyZ3NpZHV6cTJkem5zajNpdzBhdG1samg3OjJMSTFEVTM1MFVCQks1ODRCTFVBODBFTTU1V0RQRDNXRDI0Qko2Q0I5VzNFSFIzS0pSSFhOSFgyVllNMlFFMVQ="},"registry.connect.redhat.com":{"email":"rhpds-admins@redhat.com","auth":"NTE1NDg0ODB8dWhjLTFGckdzSURVWlEyRHpuU0ozaVcwQXRtTEpoNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpPR1prTVdJNFpqYzJOamcwTmpKbVlXTTRaVFpsWVRnd09EUTJOMkkzTnlKOS5YUmQ5LS1LQ3kzVlpVbF9ldTc0THpQMFEzOVYwRUVfeWRZOE5pVGRScUlyd2hVRHYtcFF2ZEtLV1ZpVmlaQWF0QkhEUVdmVDB1Z2pfTWIzYmNPUktqSXdBNldQTXYxWTc1RmhYQUg1S2Myc3lnSHVxWTRfZlhSOXJnbW42N0l0MmhiUXJyb3BBNXlaYXpXSzhPeTBJb29VWFAteDBPUjZ2VDJTVGktbm5sblBLbEFSWTBEZkxJYmk3OHZlZXFadUpyUDl4SzlXdnRaOEZOREpzQnlUc2VmeFRoVmtLMDVwVDlhTk9nTkxITGJMeU5sdEc1RE9xU1JiZ1hLMDJ6RXNaU3BwYmZLdVAwNVJYQWljQy14WEZiamtLaFpkYTgwV3lnZDJKcTZXWVF3WW83ZXgtLUh1MEpKeXBTczRINVY0Nm50dTNVRlNVUERBZEJ5VmVDU2RxckpzUWZoSmlpLVdJbXdjWnp6LUNwTlRfNVo0ei1WUkc0aV9hVF9TWnVkQzVySmFLdFpHS1RQWlg0SDlNLWxDeFlHZDJNYzhuWlc4NWVUeTJPYnBVOHA2S19sU3A3Wm15RzhEbWh6bFAtYTQzb0J1V3hJTHg3Y283U3BkOFRyYVNRbjVnaFpvc0VKZGp6X2ljTlFhVktNazFHQjEwbU1uOXJBeGdUcm5qU09aSEZvcXdmX2Y2dnZFWi0ySUp2Qk91UUZRQThsZDlzRDVDb1ZWNEdwTWx1Rl8zZGJqcXhuVTE0WXdHT2RhSldSOEtMTlFwbU9RV0JrWFJIcVpwN01UT0ZDX0dMVDRWeGNTMXhva0p6RUFxN1c4NzBSQVo4VnAtUGdscEJCc2RDT2tfdGNCNEY5T2hkZ0NPb3JMNHJkZmp6cEJobUZuMEhzVkFFNGJkaWhfRjNGSQ=="},"provision.nw979.dynamic.opentlc.com:5000":{"email":"dummy@redhat.com","auth":"ZHVtbXk6ZHVtbXk="}}}'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIF+TCCA+GgAwIBAgIUaBoUjnkAiou8kcpcCeUMe8EDU/EwDQYJKoZIhvcNAQEL
  BQAwgYsxCzAJBgNVBAYTAlVTMRYwFAYDVQQIDA1Ob3J0aENhcm9saW5hMRAwDgYD
  VQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdSZWQgSGF0MRIwEAYDVQQLDAlNYXJrZXRp
  bmcxLDAqBgNVBAMMI3Byb3Zpc2lvbi5udzk3OS5keW5hbWljLm9wZW50bGMuY29t
  MB4XDTIwMTAyMTA0MzQyMFoXDTIxMTAyMTA0MzQyMFowgYsxCzAJBgNVBAYTAlVT
  MRYwFAYDVQQIDA1Ob3J0aENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYD
  VQQKDAdSZWQgSGF0MRIwEAYDVQQLDAlNYXJrZXRpbmcxLDAqBgNVBAMMI3Byb3Zp
  c2lvbi5udzk3OS5keW5hbWljLm9wZW50bGMuY29tMIICIjANBgkqhkiG9w0BAQEF
  AAOCAg8AMIICCgKCAgEAuGQ1smKvBSigIyD6Ho4UsRIZbPYrNJNKT0dLQS6XwCgc
  mgfaJGnLzTwt8AugySypTUCwJyCDlY35ccc3IOuxIfhQtdKtGjfX5sJ84bZqgogG
  8X7QdOfIRYfacJ8PHlDsfK0Gksaofz04bG3naW8GAavLFQOlPepZLmrwTEF4Chwd
  ATmDqy9P1K4VGcfV/AJLFfZnhaOfg5mnx1hVaHNEc6xoUnqu1/ydsXRXWLYlWAS9
  rfsTNSITYdIF314gJet0uLIVil0w5+HsID3Jh0h8sYfm9y/Hh1YQnw2aqTXvVJmh
  P9zhryJJWBPj7obN5SFYrzlW3I6KCCWztZu8uql8KAz2FkyDB7egv/QXcnixGP1r
  2PW9w3dVYB5thEHzSR+h1Bw9MC9fNNRiz6OKxFxHgazFNZfv6OuTl5fsUPGv/2s+
  WSifRxweSpaX2MfAPnrwq6LeUxiUhB9v9FdDfCN0dCbetFwJCOuSez6JIpR8g3kw
  Dg4bV0JWuIQA540HMxFOobqrOFFoYtWC7K4ITdw6ZBfNMWMVyw0sleCQpWcwGFaN
  pdXnjL/ycclOlVa1Vvi1NqqyX8zdkC05EOL6HrbxYni1/nl99L2kObY0IKuNC3ML
  +Qi5/oHOCshfDBpZleU+qV5XlEc0+Gx6vPm+ktm8bT3GcCq/POMq6A2TstZtajEC
  AwEAAaNTMFEwHQYDVR0OBBYEFM9kFxSl0Cl1txdigvE61L+Pe9YwMB8GA1UdIwQY
  MBaAFM9kFxSl0Cl1txdigvE61L+Pe9YwMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
  hvcNAQELBQADggIBAJpG2zQ1pgtGMSJGfSXI9g0wnMPApj35cU1neC0+mI7ceyRp
  hDI4mUtGDN0PfTcVCFiRy+eotmTg3l4I546jW8T1G/7DueSwN26Omh3HofKB4lpD
  zJsQFnIpGHndMRK0hxHsu+CygMOAJz7xjFaSSrewSqbHyjpb6B42Q+hk+FLAJbnd
  RAEOx0WF6bGZcCpa8+VV/bbJu0eS3Xwq0yNe/+voYGUfqQDIZEvo+8iQP9MqccLr
  asvINiEKY31SufxzLZgPZQaj+UX51CD/4JqoFH9vY5ramGwsTP2Uxr4I4z+p63wq
  cUOi674yTaNUh8iJ0/laxQOpUqIhuGUyDCTW8/Z6H3ZSQVuFAWaeOGuxM64BiRKF
  14BNopfRUmbJJ3JDMSnpIrBi76mot5QH5mTZTMSz0HClYE3KmkzR0J4gUE+w8eLN
  TZvpc+xfwzbVujx63mgTnlmlcvfPNY6ePVZ/TsVKCwa0o0EJZ5sxGaY7KY0XM0Tx
  uCtfCENd7NeZXSiTWsXuDIWcMH+pM7iHuucIbQQzfbQx86xYL8hYAuApa0AVeAfe
  PLgaylG3pUlFCsZW0Un+f6Xy3slvlfpkOWreIxc8cHFOWeVqOz8BUKZUIWoBRb0s
  W3scCqn7VYrhEW/CmFgYzvbGFgnf85Bq0pDBDLX3hEb5UKmQqGV0CN1OVJmL
  -----END CERTIFICATE-----
