port: 7890
socks-port: 7891

# `allow-lan` must be true in your config.yaml
allow-lan: true
external-controller: 0.0.0.0:18080

# dashboard folder
# external-ui: /ui
mode: Rule

hosts:
  'registry.redhat.ren': 127.0.0.1

Proxy:
- name: "socks"
  type: socks5
  server: 192.168.253.1
  port: 5085

Proxy Group:
- name: Proxy
  type: select
  proxies:
    - socks

Rule:
- DOMAIN-SUFFIX,redhat.ren,DIRECT
- FINAL,Proxy



