---
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: nttmec-cpu
  namespace: nvidia
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        nttmec-cpu: "true"
    spec:
      nodeSelector:
        # type: infra
        kubernetes.io/hostname: node3.sigma.cmri
      serviceAccountName: mysvcacct
      containers:
        - name: nttmec-cpu-test
          image: "registry.sigma.cmri/test/nttmec_cpu:wzh"
          imagePullPolicy: Always
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: NVIDIA_REQUIRE_CUDA
              value: "cuda>=5.0"
          command: ['bash']
          args: ["/opt/start.sh"]
          livenessProbe:
            exec:
              command:
                - echo
                - ok
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop: ["ALL"]
          #   seLinuxOptions:
          #     type: nvidia_container_t
          ports:                              
            - containerPort: 8080
              protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: nttmec-cpu
spec:
  selector:                  
    nttmec-cpu: "true"
  ports:
  - port: 8080               
    protocol: TCP
    targetPort: 8080      