---
apiVersion: v1
kind: Pod
metadata:
  name: nttmec-cpu
  namespace: nvidia
  labels:
    nttmec-cpu: "true"
spec:
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/hostname: node3.sigma.cmri
  serviceAccountName: mysvcacct
  containers:
    - name: nttmec-cpu-test
      image: "registry.sigma.cmri/test/nttmec_cpu:wzh"
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=5.0"
      command: ['bash']
      args: ["/opt/start.sh"]
      # securityContext:
      #   allowPrivilegeEscalation: false
      #   capabilities:
      #     drop: ["ALL"]
      #   seLinuxOptions:
      #     type: nvidia_container_t
      ports:                              
      - containerPort: 8080
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nttmec-cpu
spec:
  selector:                  
    nttmec-cpu: "true"
  ports:
  - port: 8080               
    protocol: TCP
    targetPort: 8080      