apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
  namespace: istio-operator
spec:
  deployment_type: openshift
  istio:
    authentication: true
    community: false
    prefix: registry.paas.com/openshift-istio-tech-preview/
    version: latest
  jaeger:
    prefix: registry.paas.com/distributed-tracing-tech-preview/
    version: latest
    elasticsearch_memory: 1Gi
  kiali:
    username: username
    password: password
    prefix: registry.paas.com/openshift-istio-tech-preview/
    version: latest
  launcher:
    openshift:
      user: admin
      password: redhat
    github:
      username: username
      token: token
    catalog:
      filter: booster.mission.metadata.istio
      branch: master
      repo: http://10.252.166.110/wangzhen/launcher-booster-catalog.git
  threeScale:
    enabled: false
    prefix: registry.paas.com/openshift-istio-tech-preview/
    version: latest
    adapter:
      listenAddr: 3333
      logLevel: info
      logJSON: true
      reportMetrics: true
      metricsPort: 8080
      cacheTTLSeconds: 300
      cacheRefreshSeconds: 180
      cacheEntriesMax: 1000
      cacheRefreshRetries: 1
      allowInsecureConn: false
      clientTimeoutSeconds: 10