apiVersion: v1
baseDomain: redhat.ren
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp4
networking:
  clusterNetworks:
  - cidr: 10.254.0.0/16
    hostPrefix: 24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"registry.redhat.ren": {"auth": "ZHVtbXk6ZHVtbXk=","email": "noemail@localhost"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSVLJ+1xZpX5BHZonzi3mumhL5En191WdnunX8dXz093wAOvm7XRtaQFWswHD4s8LAkg7Phhfa1V8bA4oRVJjM0vL6vzpalkrpBiR4Rqr9pGbHSjLSgxSGl74uw084UsJiWBKYCzCc3EzA2A5ywyRELYExZqxT8+QE2jN1vDV/sdZkpW0ok/flGb2AJ263m4bErbOUcLk6LIkrw2cQ71+jDVPwbaEB+k0md19t8oW+zT2AshkRVd5ePATOAIGpZYgxJOVLE2RzXdIcmPAKdUHIWNwluZGMUdH+rdxEFpbaFpuYLod4UCS8g57Bu75ISmvmkV/vkAsHM1nPnq9tFAI3 root@base-pvg.redhat.ren'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIDszCCApugAwIBAgIJAJQwfcVBr3aZMA0GCSqGSIb3DQEBCwUAMHAxCzAJBgNV
  BAYTAkNOMQswCQYDVQQIDAJHRDELMAkGA1UEBwwCU1oxGDAWBgNVBAoMD0dsb2Jh
  bCBTZWN1cml0eTEWMBQGA1UECwwNSVQgRGVwYXJ0bWVudDEVMBMGA1UEAwwMKi5y
  ZWRoYXQucmVuMB4XDTE5MTIwOTA3MzEyNloXDTI5MTIwNjA3MzEyNlowcDELMAkG
  A1UEBhMCQ04xCzAJBgNVBAgMAkdEMQswCQYDVQQHDAJTWjEYMBYGA1UECgwPR2xv
  YmFsIFNlY3VyaXR5MRYwFAYDVQQLDA1JVCBEZXBhcnRtZW50MRUwEwYDVQQDDAwq
  LnJlZGhhdC5yZW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDp7sUN
  X8ij7t71gZwPkIVmNK8jduow8DwMxTofbe0mXhJWx27jF5l2DzZcVys/T6RT65x8
  plSg6c5HnkDMADv1AJr4fRkAlVbXMuUn2mQym8P+QJskqp98bbHhi3GtpoPD/ICl
  EToZvopuo/+kL+JzGbrZNMS5khnMCRVyVGQiPHSnaNSrrjj5mznqXHcojgEIywSs
  JAmWAn14BLFYfbMHEsWZn1Y/FP1LgFoFTEvZRhMsJ5gWfX8zCCPEyvNZFyrjkhUo
  ToeN17HdgRvh/sTMVloq6Bz4/sgbJut46ZLIa3igt9IAgNlOZ4Plk0ipQSVrKGiO
  XzbH9yOu2PiWpXUFAgMBAAGjUDBOMB0GA1UdDgQWBBTWEnTR2ymU1yphjXxGZuev
  pTi60DAfBgNVHSMEGDAWgBTWEnTR2ymU1yphjXxGZuevpTi60DAMBgNVHRMEBTAD
  AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAd2anWY7d/3XGps7WbGgm8+RBpUIfBNO6L
  FaBkfZuJ8+PBIgA7o3zLVxRcc+W9lS9uH+crEBnB9fYL06aR04S4W82eF28lToy4
  ChH755NCapbmMg33A5HJR9JRPR/YFOgiewX+nFahuu2EnaK4VQaYXr/5273GH8W4
  I7D3OknKeDCq+lzImge1mD4NMC6R2SwBXUNzO54J0wFJtzySyu1uuREOm22bt5Ph
  AtfRTmLLSNBXVu/DsmBf2ZwHDK+NRYWNfpe2nA+E/o5eZFnJvHkNALG3QOKNtdaR
  HMtBlV/jJymNZSBk4upvTCjfxVaDuiY1Ts5LzysKt45MXZWy9C20
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.redhat.ren:5443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.redhat.ren:5443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev