apiVersion: v1
baseDomain: redhat.ren 
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 1 
metadata:
  name: ocp41demo 
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: 
  # goto here to get
  # https://cloud.redhat.com/openshift/install/aws/user-provisioned
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjb4BqwVYPZeMhUePKeuwaf4qsO76v7Y1onRwPAPBskpnI663cWUaYTvKWMgkdhCRvKszbpAcOgHhuyjsHfcpcvpIAVURU2B2p/qtZoQoPP0a4uW7IguwRynn3IJZ/hp/K+dcsd1Oov2GPqgj0E/w5V6yPGn34PK2l01dDms4hHZNPnC6c2H+WukIwflLWDrE7/Q+3m3MuFkl5hxJgTliISg8rZjdTrzmixOtcOxaPQC98/HHWx24j38E9S1Zfx8UL8VURFeFIFQ1Y9zKiE+gSK38UBglPbReU1gVvokPQT+KteTPc6rDKp/m6RBSK4I8E3gq/BhM0PzxTLywqUQ7X ec2-user@ip-172-31-17-41.us-west-1.compute.internal' 