---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flexran-binary-release
  name: flexran-binary-release
spec:
  nodeSelector:
     testnode: worker-mb
  containers:
  - securityContext:
      privileged: false
      capabilities:
        add:
          #- SYS_ADMIN
          - IPC_LOCK
          - SYS_NICE
    command:
      - sleep
      - infinity
    tty: true
    stdin: true
    image: flexran.docker.registry/flexran_vdu:21.11
    name: flexran-container1
    resources:
      requests:
        memory: "24Gi" 
        intel.com/intel_fec_5g: '1'
        intel.com/intel_sriov_dpdk_port0: '2'
        hugepages-1Gi: 24Gi  
      limits:
        memory: "24Gi"
        intel.com/intel_fec_5g: '1'
        intel.com/intel_sriov_dpdk_port0: '2'
        hugepages-1Gi: 24Gi
    volumeMounts:
    - name: hugepage
      mountPath: /hugepages
    - name: varrun
      mountPath: /var/run/dpdk
      readOnly: false
    - name: oneapi
      mountPath: /opt/intel/
      readOnly: true
    - name: tests
      mountPath: /root/flexran/tests
      readOnly: false
    - name: sys
      mountPath: /sys/
      readOnly: false

  - securityContext:
      privileged: false
    command: [ "/bin/sh","-c","--" ]
    args: ["cp -r /opt/intel/oneapi /opt/oneapi ; top"]
    tty: true
    stdin: true
    env:
    image: intel/oneapi-basekit:devel-centos8
    name: flexran-icx
    volumeMounts:
    - name: oneapi
      mountPath: /opt/oneapi
      readOnly: false
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: varrun
    emptyDir: {}
  - name: oneapi
    emptyDir: {}
  - name: tests
    hostPath:
      path: "/home/tmp_flexran/tests"
  - name: sys
    hostPath:
      path: "/sys/"


---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flexran-oru
  name: flexran-oru
spec:
  nodeSelector:
     testnode: worker-mb
  containers:
  - securityContext:
      privileged: false
      capabilities:
        add:
          #- SYS_ADMIN
          - IPC_LOCK
          - SYS_NICE
    command:
      - sleep
      - infinity
    tty: true
    stdin: true
    image: flexran.docker.registry/flexran_vdu:21.11
    name: flexran-oru
    resources:
      requests:
        memory: "32Gi"  #8
        intel.com/intel_sriov_dpdk_port1: '2'
        hugepages-1Gi: 32Gi   #16
      limits:
        memory: "32Gi"
        intel.com/intel_sriov_dpdk_port1: '2'
        hugepages-1Gi: 32Gi
    volumeMounts:
    - name: hugepage
      mountPath: /hugepages
    - name: varrun
      mountPath: /var/run/dpdk
      readOnly: false
    - name: oneapi
      mountPath: /opt/intel/
      readOnly: true
    - name: tests
      mountPath: /root/flexran/tests
      readOnly: false
    - name: sys
      mountPath: /sys/
      readOnly: false
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: varrun
    emptyDir: {}
  - name: oneapi
    emptyDir: {}
  - name: tests
    hostPath:
      path: "/home/tmp_flexran/tests"
  - name: sys
    hostPath:
      path: "/sys/"
