apiVersion: v1
kind: Pod
metadata:
  name: webcache-001
  namespace: zxcdn
  labels: 
    pod: webcache-001
  annotations:
    k8s.v1.cni.cncf.io/networks: '
    [{
      "name": "webcache-001-macvlan",
      "default-route": ["39.134.201.94"] 
    }]'
spec:
  nodeSelector:
    kubernetes.io/hostname: 'worker-1.ocpsc.redhat.ren'
  restartPolicy: Always
  containers:
    - name: webcache-001-pg
      image: registry.redhat.ren:4443/zteadm/pg-img:v1.01.01.01
      imagePullPolicy: IfNotPresent
      command: ["/usr/sbin/init"]
      env:
        - name: ROOTPATH
          value: "/mnt"
      volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
  
        - name: resolv
          mountPath: /etc/resolv.conf
  
       # - name: zoneinfo
       #   mountPath: /usr/share/zoneinfo
        - name: cacherule-volumes
          mountPath: /tmp

        - name: pg-volumes
          mountPath: /mnt
  
      resources:
        requests:
          cpu: 1.0
          memory: 8Gi
        limits:
          cpu: 1.0
          memory: 8Gi
      securityContext:
        privileged: true
  
    - name: webcache-001-main
      image: registry.redhat.ren:4443/zteadm/zxcdn-cache-webcache-img:6.01.04.03-0421
      imagePullPolicy: IfNotPresent
      command: ["/usr/sbin/init"]
      
      # ports:
      # - name: sshd-port
      #   containerPort: 22
      #   hostPort: 22
      # - name: ires-port
      #   containerPort: 9780
      #   hostPort: 9780
      # - name: ztetool-port
      #   containerPort: 6800
      #   hostPort: 6800
      # - name: mgr-port
      #   containerPort: 6510
      #   hostPort: 6510
      # - name: svr-port
      #   containerPort: 6520
      #   hostPort: 6520
  
      volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        
        - name: resolv
          mountPath: /etc/resolv.conf
        
       # - name: zoneinfo
       #   mountPath: /usr/share/zoneinfo
      
        - name: dfs-home
          mountPath: /home/zxdfs
    
        - name: dfs-mnt
          mountPath: /mnt/zxdfs
        
        - name: zxagent-log-volumes
          mountPath: /home/zxagent/log
        - name: zxagent-etc-volumes
          mountPath: /home/zxagent/etc
    
        - name: init-configmap-volumes
          mountPath: /home/zte_node/ztetool.ini
          subPath: ztetool.ini    
        - name: zte-node-logs-volumes
          mountPath: /home/zte_node/log/ 
        
        - name: init-configmap-volumes
          mountPath: /home/init/init.conf
          subPath: init.conf
          
        - name: dfs-stat-volumes
          mountPath: /home/container/host_dfsstat
    
        - name: webcache-config-volumes
          mountPath: /home/persistence
    
        - name: webcache-nginx-log-volumes
          mountPath: /home/zxcdn/webcache/nginx/logs
    
        - name: webcache-tomcat-log-volumes
          mountPath: /home/zxcdn/webcache/tomcat/logs/
    
        - name: cacherule-volumes
          mountPath: /tmp
      resources:
        requests:
          cpu: 8.0
          memory: 48Gi
        limits:
          cpu: 8.0
          memory: 48Gi
      securityContext:
        privileged: true

  serviceAccount: zxcdn-app
  volumes:
    - name: host-time
      hostPath:
        path: /etc/localtime
  
    - name: resolv
      hostPath:
        path: /etc/resolv.conf
  
    #- name: zoneinfo
    #  hostPath:
    #    path: /usr/share/zoneinfo
  
    - name: dfs-home
      hostPath:
        path: /data_mix/home/zxdfs
    
    - name: dfs-mnt
      hostPath:
        path: /data_mix/mnt/zxdfs
  
    - name: pg-volumes
      hostPath: 
        path: /data_mix/ztecdn/webcache-001/mnt
  
    - name: zxagent-log-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-001/zxagent/logs
    - name: zxagent-etc-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-001/zxagent/etc
  
    - name: zte-node-config-volumes
      hostPath:
        path: /home/docker/ztecdn/webcache-001/zte_node/etc
    - name: zte-node-logs-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-001/zte_node/logs
      
    - name: init-configmap-volumes
      configMap:
        name: webcache-001-config
  
    - name: webcache-config-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-001/config
  
    - name: dfs-stat-volumes
      hostPath:
        path: /dev/shm/dfsstat
        type: FileOrCreate
  
    - name: webcache-nginx-log-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-001/nginx/logs
  
    - name: webcache-tomcat-log-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-001/tomcat/logs
    - name: cacherule-volumes
      hostPath:
        path: /tmp/webcache-001/cacherule
---
apiVersion: v1
kind: Pod
metadata:
  name: webcache-002
  namespace: zxcdn
  labels: 
    pod: webcache-002
  annotations:
    k8s.v1.cni.cncf.io/networks: '
    [{
      "name": "webcache-002-macvlan",
      "default-route": ["39.134.201.94"] 
    }]'
spec:
  nodeSelector:
    kubernetes.io/hostname: 'worker-1.ocpsc.redhat.ren'
  restartPolicy: Always
  containers:
    - name: webcache-002-pg
      image: registry.redhat.ren:4443/zteadm/pg-img:v1.01.01.01
      imagePullPolicy: IfNotPresent
      command: ["/usr/sbin/init"]
      env:
      - name: ROOTPATH
        value: "/mnt"
      volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
  
        - name: resolv
          mountPath: /etc/resolv.conf
  
       # - name: zoneinfo
       #   mountPath: /usr/share/zoneinfo
        - name: cacherule-volumes
          mountPath: /tmp

        - name: pg-volumes
          mountPath: /mnt
  
      resources:
        requests:
          cpu: 1.0
          memory: 8Gi
        limits:
          cpu: 1.0
          memory: 8Gi
      securityContext:
        privileged: true
  
    - name: webcache-002-main
      image: registry.redhat.ren:4443/zteadm/zxcdn-cache-webcache-img:6.01.04.03-0421
      imagePullPolicy: IfNotPresent
      command: ["/usr/sbin/init"]
      
      # ports:
      # - name: sshd-port
      #   containerPort: 22
      #   hostPort: 22
      # - name: ires-port
      #   containerPort: 9780
      #   hostPort: 9780
      # - name: ztetool-port
      #   containerPort: 6800
      #   hostPort: 6800
      # - name: mgr-port
      #   containerPort: 6510
      #   hostPort: 6510
      # - name: svr-port
      #   containerPort: 6520
      #   hostPort: 6520
  
      volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        
        - name: resolv
          mountPath: /etc/resolv.conf
        
       # - name: zoneinfo
       #   mountPath: /usr/share/zoneinfo
      
        - name: dfs-home
          mountPath: /home/zxdfs
    
        - name: dfs-mnt
          mountPath: /mnt/zxdfs
        
        - name: zxagent-log-volumes
          mountPath: /home/zxagent/log
        - name: zxagent-etc-volumes
          mountPath: /home/zxagent/etc
    
        - name: init-configmap-volumes
          mountPath: /home/zte_node/ztetool.ini
          subPath: ztetool.ini    
        - name: zte-node-logs-volumes
          mountPath: /home/zte_node/log/ 
        
        - name: init-configmap-volumes
          mountPath: /home/init/init.conf
          subPath: init.conf
          
        - name: dfs-stat-volumes
          mountPath: /home/container/host_dfsstat
    
        - name: webcache-config-volumes
          mountPath: /home/persistence
    
        - name: webcache-nginx-log-volumes
          mountPath: /home/zxcdn/webcache/nginx/logs
    
        - name: webcache-tomcat-log-volumes
          mountPath: /home/zxcdn/webcache/tomcat/logs/
    
        - name: cacherule-volumes
          mountPath: /tmp
      resources:
        requests:
          cpu: 8.0
          memory: 48Gi
        limits:
          cpu: 8.0
          memory: 48Gi
      securityContext:
        privileged: true

  serviceAccount: zxcdn-app
  volumes:
    - name: host-time
      hostPath:
        path: /etc/localtime
  
    - name: resolv
      hostPath:
        path: /etc/resolv.conf
  
    #- name: zoneinfo
    #  hostPath:
    #    path: /usr/share/zoneinfo
  
    - name: dfs-home
      hostPath:
        path: /data_mix/home/zxdfs
    
    - name: dfs-mnt
      hostPath:
        path: /data_mix/mnt/zxdfs
  
    - name: pg-volumes
      hostPath: 
        path: /data_mix/ztecdn/webcache-002/mnt
  
    - name: zxagent-log-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-002/zxagent/logs
    - name: zxagent-etc-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-002/zxagent/etc
  
    - name: zte-node-config-volumes
      hostPath:
        path: /home/docker/ztecdn/webcache-002/zte_node/etc
    - name: zte-node-logs-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-002/zte_node/logs
      
    - name: init-configmap-volumes
      configMap:
        name: webcache-002-config
  
    - name: webcache-config-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-002/config
  
    - name: dfs-stat-volumes
      hostPath:
        path: /dev/shm/dfsstat
        type: FileOrCreate
  
    - name: webcache-nginx-log-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-002/nginx/logs
  
    - name: webcache-tomcat-log-volumes
      hostPath:
        path: /data_mix/ztecdn/webcache-002/tomcat/logs
    - name: cacherule-volumes
      hostPath:
        path: /tmp/webcache-002/cacherule

---

