apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-web-ui-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-web-ui-operator
  template:
    metadata:
      labels:
        name: kubevirt-web-ui-operator
    spec:
      serviceAccountName: kubevirt-web-ui-operator
      containers:
        - name: kubevirt-web-ui-operator
          securityContext:
            runAsUser: 0
          image: registry.redhat.ren/kubevirt/kubevirt-web-ui-operator:v1.4.0
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - kubevirt-web-ui-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubevirt-web-ui-operator"
