---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-web-ui-operator
  namespace: openshift-console
subjects:
- kind: ServiceAccount
  name: kubevirt-web-ui-operator
  namespace: kubevirt-web-ui
roleRef:
  kind: Role
  name: kubevirt-web-ui-operator
  apiGroup: rbac.authorization.k8s.io