---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kubevirt-web-ui-operator
  namespace: openshift-console
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - 'get'
