apiVersion: v1
kind: Pod
metadata:
  name: testpod1-1
spec:
  containers:
  - name: appcntr1 
    image: registry.crmi.cn:5021/centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    volumeMounts:
      # - mountPath: /etc/pcidp/
      #   name: config
      #   readOnly: true
      - name: config-volume
        mountPath: /etc/pcidp/config.json
        subPath: config.json
  volumes:
    # - name: config
    #   hostPath:
    #     path: /etc/pcidp/
    - name: config-volume
      configMap:
        name: sriovdp-config