apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.cnv.io/win10: Microsoft Windows 10
  selfLink: /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachines/win7
  resourceVersion: '1410278'
  name: win7
  uid: 4ba8d5ca-72d4-11e9-83a9-7ca23e90ca35
  creationTimestamp: '2019-05-10T03:32:53Z'
  generation: 1
  namespace: default
  labels:
    app: win7
    flavor.template.cnv.io/Custom: 'true'
    os.template.cnv.io/win10: 'true'
    template.cnv.ui: openshift_win2k12r2-generic-medium
    vm.cnv.io/template: win2k12r2-generic-medium
    workload.template.cnv.io/generic: 'true'
spec:
  dataVolumeTemplates:
    - metadata:
        name: rootdisk-win7
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
        source:
          http:
            url: >-
              http://192.168.39.31:8000/cn_windows_7_ultimate_with_sp1_x64_dvd_618537.iso
  running: false
  template:
    metadata:
      labels:
        vm.cnv.io/name: win7
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: sata
              name: rootdisk
            - name: virtiocontainerdisk
              bootOrder: 2
              cdrom:
                bus: sata
          interfaces:
            - bridge: {}
              model: e1000e
              name: nic0
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
        resources:
          requests:
            memory: 4G
      networks:
        - name: nic0
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - dataVolume:
            name: rootdisk-win7
          name: rootdisk
        - containerDisk:
            image: kni-registry.redhat.ren:5021/cnv-tech-preview/virtio-win
          name: virtiocontainerdisk
        - containerDisk:
            image: kni-registry.redhat.ren:5021/win7_install
          name: win7installdisk
