apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.cnv.io/rhel7.0: Red Hat Enterprise Linux 7.0
  selfLink: /apis/kubevirt.io/v1alpha3/namespaces/test-wzh/virtualmachines/wzh1
  resourceVersion: '1318720'
  name: wzh1
  uid: 68c39993-4633-11e9-95bf-98be94413f0a
  creationTimestamp: '2019-03-14T08:30:22Z'
  generation: 1
  namespace: test-wzh
  labels:
    flavor.template.cnv.io/small: 'true'
    os.template.cnv.io/rhel7.0: 'true'
    template.cnv.ui: openshift_rhel-generic
    workload.template.cnv.io/generic: 'true'
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        vm.cnv.io/name: wzh1
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              name: nic0
          rng: {}
        machine:
          type: ''
        resources:
          requests:
            memory: 2G
      networks:
        - name: nic0
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - containerDisk:
            image: 'registry.redhat.ren/vmidisks/rhel7.6:latest'
          name: rootdisk
        - cloudInitNoCloud:
            userDataBase64: >-
              IyEvYmluL2Jhc2gKc2V0IC14CmNhdCAvZXRjL3Bhc3N3ZApjYXQgL2V0Yy9zaGFkb3cKdXNlcmFkZCAtcCAkKCBvcGVuc3NsIHBhc3N3ZCAtMSB3emh3emggKSB3emggLXMgL2Jpbi9iYXNoIC1HIHdoZWVsCmNhdCAvZXRjL3NoYWRvdw==
          name: cloudinitdisk
status:
  created: true
  ready: true
