apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  additionalNetworks:
  - name: slbl7-001-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.69/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
        type: static
    type: SimpleMacvlan
  - name: ottcache-001-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.70/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
        type: static
    type: SimpleMacvlan
  - name: ottcache-002-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.71/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
        type: static
    type: SimpleMacvlan
  - name: ottcache-003-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.72/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
        type: static
    type: SimpleMacvlan
  - name: slb-001-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.75/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
        type: static
    type: SimpleMacvlan
  - name: slb-002-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.76/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
        type: static
    type: SimpleMacvlan
  - name: webcache-001-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.77/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
        type: static
    type: SimpleMacvlan
  - name: webcache-002-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.134.201.78/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.201.94
        type: static
    type: SimpleMacvlan
  - name: slb-011-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.137.101.50/25
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.137.101.126
        type: static
    type: SimpleMacvlan
  - name: slb-012-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.137.101.51/25
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.137.101.126
        type: static
    type: SimpleMacvlan
  - name: webcache-011-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.137.101.52/25
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.137.101.126
        type: static
    type: SimpleMacvlan
  - name: webcache-012-macvlan
    namespace: zxcdn
    simpleMacvlanConfig:
      ipamConfig:
        staticIPAMConfig:
          addresses:
          - address: 39.137.101.54/25
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.137.101.126
        type: static
    type: SimpleMacvlan
  - name: redhat-001-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.134.204.76/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.204.65
  - name: redhat-002-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.134.204.77/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.204.65
  - name: redhat-003-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.134.204.78/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.204.65
  - name: redhat-004-macvlan
    namespace: zxcdn
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 39.134.204.72/27
          routes:
          - destination: 0.0.0.0/0
            gateway: 39.134.204.65            
            

