apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-09-16T13:53:18Z'
  name: zw-facego
  namespace: zhuowang
  resourceVersion: '4224929'
  selfLink: /apis/route.openshift.io/v1/namespaces/zhuowang/routes/zw-facego
  uid: 56902a44-d889-11e9-bf41-04fe8dbed9ee
spec:
  host: zw-facego-zhuowang.apps.sigma.cmri
  port:
    targetPort: http
  to:
    kind: Service
    name: zw-facego
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-16T13:53:23Z'
          status: 'True'
          type: Admitted
      host: zw-facego-zhuowang.apps.sigma.cmri
      routerName: router
      wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-09-16T13:37:07Z'
  name: zw-ocean-socket
  namespace: zhuowang
  resourceVersion: '4220804'
  selfLink: /apis/route.openshift.io/v1/namespaces/zhuowang/routes/zw-ocean-socket
  uid: 1405e72d-d887-11e9-bf41-04fe8dbed9ee
spec:
  host: zw-ocean-socket-zhuowang.apps.sigma.cmri
  to:
    kind: Service
    name: zw-ocean-socket
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-16T13:37:12Z'
          status: 'True'
          type: Admitted
      host: zw-ocean-socket-zhuowang.apps.sigma.cmri
      routerName: router
      wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-09-16T13:36:33Z'
  name: zw-nginx-oc
  namespace: zhuowang
  resourceVersion: '4220649'
  selfLink: /apis/route.openshift.io/v1/namespaces/zhuowang/routes/zw-nginx-oc
  uid: ff74e23d-d886-11e9-bf41-04fe8dbed9ee
spec:
  host: zw-nginx-oc-zhuowang.apps.sigma.cmri
  port:
    targetPort: pic
  to:
    kind: Service
    name: zw-nginx-oc
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-16T13:36:38Z'
          status: 'True'
          type: Admitted
      host: zw-nginx-oc-zhuowang.apps.sigma.cmri
      routerName: router
      wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-09-16T13:17:01Z'
  labels:
    app: nginx-oc-front
  name: nginx-oc-front
  namespace: zhuowang
  resourceVersion: '4215646'
  selfLink: /apis/route.openshift.io/v1/namespaces/zhuowang/routes/nginx-oc-front
  uid: 452d6723-d884-11e9-bf41-04fe8dbed9ee
spec:
  host: nginx-oc-front-zhuowang.apps.sigma.cmri
  port:
    targetPort: 10001-tcp
  to:
    kind: Service
    name: nginx-oc-front
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-16T13:17:06Z'
          status: 'True'
          type: Admitted
      host: nginx-oc-front-zhuowang.apps.sigma.cmri
      routerName: router
      wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-09-16T12:52:04Z'
  name: zw-ocean-manager
  namespace: zhuowang
  resourceVersion: '4209245'
  selfLink: /apis/route.openshift.io/v1/namespaces/zhuowang/routes/zw-ocean-manager
  uid: c8d91ba7-d880-11e9-bf41-04fe8dbed9ee
spec:
  host: zw-ocean-manager-zhuowang.apps.sigma.cmri
  port:
    targetPort: web1
  to:
    kind: Service
    name: zw-ocean-manager
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-16T12:52:09Z'
          status: 'True'
          type: Admitted
      host: zw-ocean-manager-zhuowang.apps.sigma.cmri
      routerName: router
      wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-09-16T11:10:00Z'
  name: zw-api-oc
  namespace: zhuowang
  resourceVersion: '4183790'
  selfLink: /apis/route.openshift.io/v1/namespaces/zhuowang/routes/zw-api-oc
  uid: 86385996-d872-11e9-bf41-04fe8dbed9ee
spec:
  host: zw-api-oc-zhuowang.apps.sigma.cmri
  to:
    kind: Service
    name: zw-api-oc
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-16T11:10:05Z'
          status: 'True'
          type: Admitted
      host: zw-api-oc-zhuowang.apps.sigma.cmri
      routerName: router
      wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-09-16T10:19:44Z'
  name: zw-rtmp-server
  namespace: zhuowang
  resourceVersion: '4171316'
  selfLink: /apis/route.openshift.io/v1/namespaces/zhuowang/routes/zw-rtmp-server
  uid: 80794f9c-d86b-11e9-bf41-04fe8dbed9ee
spec:
  host: zw-rtmp-server-zhuowang.apps.sigma.cmri
  to:
    kind: Service
    name: zw-rtmp-server
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-09-16T10:19:48Z'
          status: 'True'
          type: Admitted
      host: zw-rtmp-server-zhuowang.apps.sigma.cmri
      routerName: router
      wildcardPolicy: None
