apiVersion: v1
data:
  extra_conf_gpu.txt: "\uFEFF#配置文件中的路径不能有空格\ndetect_dir=./models_gpu/faceDetector3_27    #检测模型文件夹 (gpuid >= 0 时有效) \ndetect_face_model=./models_gpu/faceDetector3_27/faceDetector3.mdl                  #检测人脸的模型 (gpuid < 0 时有效)\nkey_point_dir=./models_gpu/FacialPoint9 #关键点模型文件夹\nhash_model=./models_gpu/recoModels_hash_0129_to_fude/CWR_Config2.5s_x_h.xml\nrecog_model=./models_gpu/recoModels_190402_rt_pa_tensor/CWR_Config3.0_1_1.xml\n\nage_and_gender_dir=age_and_gender/CWR_Config2.0.xml                  #年龄和性别模型路径, 该路径为关键点模型文件夹下的相对路径\nageGroup_and_nationality_dir=age_group_20180903/CWR_Config2.4.xml    #年龄段和国籍检测模型路径, 该路径为关键点模型文件夹下的相对路径\nface_classfication_dir=Skin_Race/faceRace_181011/cw_race_config.xml  #注意：该模型只能用 CPU。\n\n\ndetect_age_and_gender=1          #是否开启年龄性别判断，     1表示开启，0表示关闭\ndetect_ageGroup_and_nationality=0 #是否开启年龄段和国籍判断， 1表示开启，0表示关闭\ndetect_face_classfication=1      #是否开启人种检测判断，     1表示开启，0表示关闭\n\n#人脸质量分开关：None, All, Img, Skin, Pose, EyeOpen, MouthOpen, BlackFrameGlass, SunGlass, Occlusion\n#使用 '|' 合并多个选项，例如: EyeOpen | MouthOpen | SunGlass (大小写不限)\n#这些开关影响一些返回的分数是否有效，请参考库的头文件。\n#face_quality_switches=Img|Skin|Pose|Occlusion|SunGlass|BlackFrameGlass #(3.0.9)人脸质量分开关，默认值: ALL\nface_quality_switches=ALL #(3.0.9)人脸质量分开关，默认值: ALL\n\nauto_detect_idcard=1 #是否开启判断证件照，1开启，0关闭\nskip_idcard_quality_detection=0 #是否跳过证件照质量分检测，1开启，0关闭\n\n\nraceThreshold = 0.99   # 人种分类阈值\n\nhashPassRate=0.04 #hash 初筛选通过率, 取值范围 0 到 1.  例如 0.04 的哈希通过率表示使用哈希特征进行筛选后, 只保留 4% 的特征进行后续操作\n\nrerank_model=./models_gpu/ranker.xml  #rerank 模型文件\nrerank=0          #hash 初筛选后，是否启用 Ltr-Rerank ; 0-不用。1-启用（需配置 hash 模型）。\n\nselectFace=2      #(3.0.5) 选人脸策略：0-禁用，1-最大，2-居中，3-关键点可见度。\nmaxFaceCount=30   #(3.0.5) 单张图片最大人脸数 [1, 40]; 1 - 等效于禁用选人脸策略。\n\nfeatureContainsQuality=0 #(3.0.7) 特征中是否包含人脸质量分。0-不包含，1-包含（默认）。\nfeatureIsSymmetry=1      #(3.0.7) 是否使用对称特征。0-非对称特征，1-对称特征（默认）。\n\n\n\n\ndetectBatchSize = 16 # 人脸检测一次操作的图像, 推荐最大值: 16\nfeatureBatchSize = 8  # 特征提取一次操作的图像, 推荐最大值: 8\n\n\nnDetectThread=3  #人脸检测线程数\nnFeatureThread=1 #特征提取线程数\nGpuID=0\n# GpuID=1\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: '2019-09-16T14:13:58Z'
  name: extra-conf-gpu
  namespace: zhuowang
  resourceVersion: '4230216'
  selfLink: /api/v1/namespaces/zhuowang/configmaps/extra-conf-gpu
  uid: 3961571d-d88c-11e9-bf41-04fe8dbed9ee
---
apiVersion: v1
data:
  config.js: |+
    window.g = {
        sys_SysTitle: '视图汇聚分析平台', // 系统名称
        sys_Copyright: 'Copyright  2019 重庆中科云从科技有限公司. All Rights Reserved. CloudWalk Technology Co., Ltd.', // 版权声明
        sys_authExpires: '为避免影响系统正常使用，请及时联系云从工作人员：400-151-5992', // 授权到期
        sys_aboutSystem: '视图汇聚分析平台', // 关于系统
        sys_version: '1.4.2', // 系统版本
        sys_defApp: '0', // 默认加载appId
        sys_monitor_logoShow: true, // 登录页显示logo
        webApi_socket: 'ws://zw-ocean-socket-zhuowang.apps.sigma.cmri/ocean/', // webSocket地址
        webApi_base: 'http://zw-ocean-manager-zhuowang.apps.sigma.cmri/ocean/', // 基础数据接口
        webApi_ocean: 'http://zw-ocean-manager-zhuowang.apps.sigma.cmri/ocean/',
        webApi_dic: 'http://zw-ocean-manager-zhuowang.apps.sigma.cmri/ocean/dic/data/ext/list', // 字典获取接口
        imgHead_url: 'http://zw-nginx-oc-zhuowang.apps.sigma.cmri/', // 图片前缀
        webApi_dpcs: ''
    };

kind: ConfigMap
metadata:
  creationTimestamp: '2019-09-16T13:06:53Z'
  name: nginx-oc-front-config
  namespace: zhuowang
  resourceVersion: '4224147'
  selfLink: /api/v1/namespaces/zhuowang/configmaps/nginx-oc-front-config
  uid: da76e9f0-d882-11e9-bf41-04fe8dbed9ee
---
apiVersion: v1
data:
  nginx.conf: "\nuser root;\n#worker_processes  auto;\nworker_processes  10;\nevents {\n    worker_connections  1024;\n}\n\nhttp {\n    client_max_body_size 600m;\n    include       mime.types;\n    default_type  application/octet-stream;\n    sendfile        on;\n    keepalive_timeout  65;\n    access_log off;\n    error_log /dev/null;\n\n    upstream ocean-server{\n        server 10.0.75.1:11006 weight=10;\n    }\n    upstream facebigdata-server{\n        server 10.128.129.219:11002 weight=10;\n    }    \n    upstream ocean-manage-server{\n        server 10.128.128.219:11007 weight=10;\n    }\n    upstream ocean-entry-http-server{\n        server 10.128.129.219:11013 weight=10;\n    }\n\n    server{\n                listen 10013;\n                location /{\n                proxy_pass http://ocean-entry-http-server;\n                expires 30d;\n                }\n    }\n\n    server{\n                listen 10007;\n                location /{\n                proxy_pass http://ocean-manage-server;\n                expires 30d;\n                }\n    }\n\n    server{\n\t\tlisten 10001;\n\t\tlocation /{\n                root /zpc/ocean-front_1.4.2;\n                autoindex on;\n                }\n     }\n    \n     server{\n                listen 10000;\n                location /{\n                alias key_cloudwalk-origin-cli.path/cloudwalk-origin-cli/;\n                autoindex on;\n                }\n     }\n     \n     server{\n                listen 10002;\n                location /{\n                proxy_pass http://facebigdata-server;\n                proxy_connect_timeout 300s;\n                proxy_send_timeout 300s;\n                proxy_read_timeout 300s;\n                expires 30d;\n                }\n     }\n\n     server{\n                listen 10006;\n                location /{\n                proxy_pass http://ocean-server;\n                expires 30d;\n                }\n     }\n    \n\n\n \n\n    server {\n\t\tlisten 10004;\n\t\tlocation /{\n\t\talias key_cloudwalk-origin-cli.path/ditu/;\n\t\tautoindex on;\n\t\t}\n          }      \n\n    server{\n\tlisten 10005;\n\n\tlocation ^~/01/A0{\n\t\talias /home/nasdata/a0;\n\t\tautoindex on;\n\t}\n\n        location ^~/01/A1{\n                alias /home/nasdata/a1;\n                autoindex on;\n        }\n\n        location ^~/01/A2{\n                alias /home/nasdata/a2;\n                autoindex on;\n        }\t\n    }\n}\nstream {\n    upstream ocean-socket {\n        least_conn;\n        server 10.128.129.219:11011 weight=5 max_fails=1 fail_timeout=10s;\n    }\n\n    server {\n        listen 10011 so_keepalive=on;\n        proxy_connect_timeout 3s;\n        proxy_pass ocean-socket;\n    }\n\n}\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: '2019-09-16T13:20:14Z'
  name: nginx-oc-front-nginxconfig
  namespace: zhuowang
  resourceVersion: '4219586'
  selfLink: /api/v1/namespaces/zhuowang/configmaps/nginx-oc-front-nginxconfig
  uid: b7aadc25-d884-11e9-bf41-04fe8dbed9ee
---
apiVersion: v1
data:
  config.properties: "\r\ncw.system.nginx-img-url=http://:10005\r\n\r\n#服务信息配置\r\n\r\n\r\nsharding.jdbc.datasource.names=ds0\r\n#\\u8BBE\\u7F6E\\u6570\\u636E\\u6E90\\u53C2\\u6570\r\nsharding.jdbc.datasource.ds0.type=com.zaxxer.hikari.HikariDataSource\r\nsharding.jdbc.datasource.ds0.driver-class-name=com.mysql.jdbc.Driver\r\nsharding.jdbc.datasource.ds0.jdbc-url=jdbc:mysql://zw-mysql-oc:3306/ocean?characterEncoding=utf8&useSSL=true\r\nsharding.jdbc.datasource.ds0.username=root\r\nsharding.jdbc.datasource.ds0.password=asdf1@34\r\n#\\u8BBE\\u7F6E\\u9ED8\\u8BA4\\u6570\\u636E\\u6E90\r\nsharding.jdbc.config.sharding.default-data-source-name=ds0\r\n\r\nserver.servlet.context-path=/ocean\r\nserver.port=11007\r\n\r\n#logs config\r\nlogging.level.root=info\r\nlogging.path=/home/logs/ocean-manage\r\ncustom.logging.config.infoMaxHistory=3d\r\ncustom.logging.config.debugMaxHistory=3d\r\ncustom.logging.config.errorMaxHistory=3d\r\n\r\n#===================================================模块配置===========================================================#\r\n#kafka配置\r\nkafka.bootstrap.servers=zw-kaf1:9092\r\nkafka.zookeeper.connect=zw-zk1:2181\r\n\r\n#------------nas存储配置 --------------#\r\n#当前服务器标识\r\ncw.nasstorage.server-deputy=01\r\n#多存储路径标识\r\ncw.nasstorage.mount-deputy=A0,A1,A2\r\n#多物理存储路径\r\ncw.nasstorage.mount-path=/home/nasdata/a0/,/home/nasdata/a1/,/home/nasdata/a2/\r\n#多存储路径权重(总计为100,权重只能整数)\r\ncw.nasstorage.weight=30,30,40\r\n#人脸图片存储目录名称\r\ncw.nasstorage.folder-facepic=facepic\r\n#全景图片存储目录名称\r\ncw.nasstorage.folder-fullpic=fullpic\r\n#底库人脸分区存储目录数量\r\ncw.nasstorage.face-group-sub-dir-count=200\r\n\r\n#------------facego引擎配置 --------------#\r\n#引擎访问路径\r\ncw.facego.engine.base-url=http://:7100\r\n#引擎访问账号\r\ncw.facego.engine.app-id=system\r\n#引擎访问密码\r\ncw.facego.engine.app-secret=12345\r\n#特征专用引擎节点\r\ncw.facego.engine.feature-url=${cw.facego.engine.base-url}\r\n#人脸识别专用引擎节点\r\ncw.facego.engine.face-recog-url=${cw.facego.engine.base-url}\r\n#人脸抓拍专用引擎节点\r\ncw.facego.engine.face-snap-url=${cw.facego.engine.base-url}\r\n#人脸工具专用引擎节点\r\ncw.facego.engine.face-tool-url=${cw.facego.engine.base-url}\r\n#聚类引擎地址\r\ncw.facego.engine.cluster-url=http://FaceGo_Cluster_ip:7100\r\n#聚类开关\r\ncw.facego.engine.cluster-switch=true\r\n#OCR专用引擎节点\r\ncw.facego.engine.ocr-url=http://key_FaceGo_ocr:20030\r\n#活体识别专用引擎节点\r\ncw.facego.engine.livedetection-url=http://:20032\r\n\r\n#------------vms引擎配置 --------------#\r\n#引擎服务ip\r\ncw.vms.engine.ip=\r\n#引擎服务端口\r\ncw.vms.engine.port=8100\r\n#引擎访问账号\r\ncw.vms.engine.app-name=admin\r\n#引擎访问密码\r\ncw.vms.engine.app-password=123456\r\n#引擎访问TOKEN\r\ncw.vms.engine.app-token=7b9c654b554c685d6d5998b49c9cd29a6e5d734b674f68429cb4d89a929c61766a456d419cb4258dab8eb58e288aa98e79\r\n\r\n#------------Redis配置--------------#\r\n# Redis数据库索引（默认为0）\r\nspring.redis.database=1  \r\n# Redis服务器地址\r\nspring.redis.host=zw-redisp\r\n# Redis服务器连接端口\r\nspring.redis.port=6379  \r\n# Redis服务器连接密码（默认为空）\r\nspring.redis.password=Anfang@123!\r\n# 连接池最大连接数（使用负值表示没有限制）\r\nspring.redis.jedis.pool.max-active=8  \r\n# 连接池最大阻塞等待时间（使用负值表示没有限制）\r\nspring.redis.jedis.pool.max-wait=-1\r\n# 连接池中的最大空闲连接\r\nspring.redis.jedis.pool.max-idle=8  \r\n# 连接池中的最小空闲连接\r\nspring.redis.jedis.pool.min-idle=0  \r\n# 连接超时时间（毫秒）\r\nspring.redis.timeout=5000\r\n\r\n#Dubbo服务消费者配置\r\ndubbo.scan.base-packages=cn.cloudwalk.ocean.web.manager.terminal.controller\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=20880\r\ndubbo.protocol.status=client\r\ndubbo.consumer.timeout=10000\r\n## Dubbo Registry\r\ndubbo.registry.address=zookeeper://zw-zk1:2181\r\ndubbo.application.qos-enable=false\r\ndubbo.config.multiple=true\r\ndubbo.consumer.check=false\r\ndubbo.registry.check=false\r\n"
kind: ConfigMap
metadata:
  creationTimestamp: '2019-09-16T14:50:09Z'
  name: ocean-manage-config
  namespace: zhuowang
  resourceVersion: '4242556'
  selfLink: /api/v1/namespaces/zhuowang/configmaps/ocean-manage-config
  uid: 47a46a9b-d891-11e9-bf41-04fe8dbed9ee
---
apiVersion: v1
data:
  config.properties: >+
    #服务监听信息

    socket.server.port=11011

    cw.system.nginx-img-url=http://:10005


    #logs config

    logging.level.root=info

    logging.path=/home/logs/ocean-socket

    custom.logging.config.infoMaxHistory=3d

    custom.logging.config.debugMaxHistory=3d

    custom.logging.config.errorMaxHistory=3d


    #======================================================模块配置========================================================#

    #kafka配置

    kafka.bootstrap.servers=zw-kaf1:9092

    kafka.zookeeper.connect=zw-zk1:2181


    #------------------------sharding-jdbc分库分表配置开始-------------------------------#

    #数据库配置，支持多数据库 中间以逗号分割

    sharding.jdbc.datasource.names=ds0


    #数据库配置

    sharding.jdbc.datasource.ds0.type=com.zaxxer.hikari.HikariDataSource

    sharding.jdbc.datasource.ds0.driver-class-name=com.mysql.jdbc.Driver

    sharding.jdbc.datasource.ds0.jdbc-url=jdbc:mysql://zw-mysql-oc:3306/ocean?characterEncoding=utf8&useSSL=true

    sharding.jdbc.datasource.ds0.username=root

    sharding.jdbc.datasource.ds0.password=asdf1@34


    #默认数据库

    sharding.jdbc.config.sharding.default-data-source-name=ds0


    #是否打印sql执行日志

    sharding.jdbc.config.sharding.props.sql.show=false


    #------------------------sharding-jdbc分库分表配置结束-------------------------------#

    schedule.server.zkAddressList=zw-zk1:2181

    schedule.server.namespace=schedule

    schedule.server.dbUrl=jdbc:mysql://zw-mysql-oc:3306/ocean?useUnicode=true&characterEncoding=utf-8&useSSL=true

    schedule.server.dbUserName=root

    schedule.server.dbPassword=asdf1@34

    schedule.server.configType=0


    #------------nas存储配置 --------------#

    #当前服务器标识

    cw.nasstorage.server-deputy=01

    #多存储路径标识

    cw.nasstorage.mount-deputy=A0,A1,A2

    #多物理存储路径

    cw.nasstorage.mount-path=/home/nasdata/a0/,/home/nasdata/a1/,/home/nasdata/a2/

    #多存储路径权重(总计为100,权重只能整数)

    cw.nasstorage.weight=30,30,40

    #人脸图片存储目录名称

    cw.nasstorage.folder-facepic=facepic

    #全景图片存储目录名称

    cw.nasstorage.folder-fullpic=fullpic

    #底库人脸分区存储目录数量

    cw.nasstorage.face-group-sub-dir-count=200



    #------------facego引擎配置 --------------#

    #引擎访问路径

    cw.facego.engine.base-url=http://:7100

    #引擎访问账号

    cw.facego.engine.app-id=system

    #引擎访问密码

    cw.facego.engine.app-secret=12345

    #聚类开关

    cw.facego.engine.cluster-switch=true

    #特征专用引擎节点

    cw.facego.engine.feature-url=${cw.facego.engine.base-url}

    #人脸识别专用引擎节点

    cw.facego.engine.face-recog-url=${cw.facego.engine.base-url}

    #人脸抓拍专用引擎节点

    cw.facego.engine.face-snap-url=${cw.facego.engine.base-url}

    #人脸工具专用引擎节点

    cw.facego.engine.face-tool-url=${cw.facego.engine.base-url}

    #聚类引擎地址

    cw.facego.engine.cluster-url=http://FaceGo_Cluster_ip:7100


    #------------Redis配置--------------#

    # Redis数据库索引（默认为0）

    spring.redis.database=1  

    # Redis服务器地址

    spring.redis.host=zw-redisp

    # Redis服务器连接端口

    spring.redis.port=6379  

    # Redis服务器连接密码（默认为空）

    spring.redis.password=Anfang@123!

    # 连接池最大连接数（使用负值表示没有限制）

    spring.redis.jedis.pool.max-active=8  

    # 连接池最大阻塞等待时间（使用负值表示没有限制）

    spring.redis.jedis.pool.max-wait=-1

    # 连接池中的最大空闲连接

    spring.redis.jedis.pool.max-idle=8  

    # 连接池中的最小空闲连接

    spring.redis.jedis.pool.min-idle=0  

    # 连接超时时间（毫秒）

    spring.redis.timeout=5000


    #抓拍入聚类引擎线程数#

    cw.cluster.async.corePoolSize=30

    cw.cluster.async.maxPoolSize=60

    cw.cluster.async.queueCapacity=60

kind: ConfigMap
metadata:
  creationTimestamp: '2019-09-16T14:48:12Z'
  name: ocean-socket-config
  namespace: zhuowang
  resourceVersion: '4246058'
  selfLink: /api/v1/namespaces/zhuowang/configmaps/ocean-socket-config
  uid: 02253609-d891-11e9-bf41-04fe8dbed9ee
---
apiVersion: v1
data:
  nginx.conf: "# zhengbin update on openshift\nuser root;\nworker_processes  10;\nevents {\n    worker_connections  1024;\n}\n\nhttp {\n    client_max_body_size 600m;\n    include       mime.types;\n    default_type  application/octet-stream;\n    sendfile        on;\n    keepalive_timeout  65;\n    access_log off;\n    error_log /dev/null;\n\n    upstream ocean-server{\n        server zw-api-oc:11006 weight=10;\n    }\n    upstream facebigdata-server{\n        server 192.168.40.116:11002 weight=10;\n    }    \n    upstream ocean-manage-server{\n        server zw-api-oc:11006 weight=10;\n    }\n    upstream ocean-entry-http-server{\n        server 192.168.40.116:11013 weight=10;\n    }\n\n\n    server{\n                listen 10006;\n                server_name localhost;\n                location /{\n                proxy_pass http://ocean-manage-server;\n                expires 30d;\n                }\n    }\n\n    server{\n\t\tlisten 10001;\n\t\tserver_name localhost;\n\t\tlocation /{\n                alias key_ocean-front/ocean-front_1.4.2/;\n                autoindex on;\n                }\n     }\n    \n     server{\n                listen 10000;\n                server_name localhost;\n                location /{\n                alias key_cloudwalk-origin-cli.path/cloudwalk-origin-cli/;\n                autoindex on;\n                }\n     }\n     \n     server{\n                listen 10002;\n                server_name localhost;\n                location /{\n                proxy_pass http://facebigdata-server;\n                proxy_connect_timeout 300s;\n                proxy_send_timeout 300s;\n                proxy_read_timeout 300s;\n                expires 30d;\n                }\n     }\n\n     server{\n                listen 10006;\n                server_name localhost;\n                location /{\n                proxy_pass http://ocean-server;\n                expires 30d;\n                }\n     }\n    \n\n\n \n\n    server {\n\t\tlisten 10004;\n\t\tserver_name localhost;\n\t\tlocation /{\n\t\talias key_cloudwalk-origin-cli.path/ditu/;\n\t\tautoindex on;\n\t\t}\n          }      \n\n    server{\n\tlisten 10005;\n\tserver_name localhost;\n\n\tlocation ^~/01/A0{\n\t\talias /home/nasdata/a0;\n\t\tautoindex on;\n\t}\n\n        location ^~/01/A1{\n                alias /home/nasdata/a1;\n                autoindex on;\n        }\n\n        location ^~/01/A2{\n                alias /home/nasdata/a2;\n                autoindex on;\n        }\t\n    }\n}\nstream {\n    upstream ocean-socket {\n        least_conn;\n        server 192.168.40.116:11011 weight=5 max_fails=1 fail_timeout=10s;\n    }\n\n    server {\n        listen 10011 so_keepalive=on;\n        proxy_connect_timeout 3s;\n        proxy_pass ocean-socket;\n    }\n\n}\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: '2019-09-16T08:44:28Z'
  name: zw-nginx-config
  namespace: zhuowang
  resourceVersion: '4162972'
  selfLink: /api/v1/namespaces/zhuowang/configmaps/zw-nginx-config
  uid: 31c2a60b-d85e-11e9-bf41-04fe8dbed9ee
