apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T06:18:57Z'
  name: zw-api-oc
  namespace: zhuowang
  resourceVersion: '4176139'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-api-oc
  uid: dd7edc96-d849-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.128.160
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32261
      port: 11006
      protocol: TCP
      targetPort: 11006
  selector:
    zw-api-oc: 'true'
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
