apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T06:20:09Z'
  name: zw-facego
  namespace: zhuowang
  resourceVersion: '4224652'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-facego
  uid: 087da10d-d84a-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.193.90
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 32748
      port: 7100
      protocol: TCP
      targetPort: 7100
    - name: http1
      nodePort: 32449
      port: 8556
      protocol: TCP
      targetPort: 7100
    - name: webpush
      nodePort: 31044
      port: 7102
      protocol: TCP
      targetPort: 7102
  selector:
    zw-facego: 'true'
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
