apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T06:37:07Z'
  name: zw-mysql-oc
  namespace: zhuowang
  resourceVersion: '4113457'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-mysql-oc
  uid: 67237d30-d84c-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.156.220
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    zw-mysql-oc: 'true'
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}