apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T06:27:20Z'
  name: zw-mobilesoldierservice
  namespace: zhuowang
  resourceVersion: '4205021'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-mobilesoldierservice
  uid: 093acace-d84b-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.6.208
  externalTrafficPolicy: Cluster
  ports:
    - name: shouji
      nodePort: 30514
      port: 18080
      protocol: TCP
      targetPort: 18080
    - name: rtsp
      nodePort: 30528
      port: 10554
      protocol: TCP
      targetPort: 10554
    - name: mqtt
      nodePort: 30493
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    zw-mobilesoldierservice: 'true'
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
