apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T06:30:00Z'
  name: zw-nginx-oc
  namespace: zhuowang
  resourceVersion: '4134636'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-nginx-oc
  uid: 68e5f72b-d84b-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.81.150
  ports:
    - name: pic
      port: 10005
      protocol: TCP
      targetPort: 10005
    - name: ocean-manager
      port: 10001
      protocol: TCP
      targetPort: 10001
    - name: ocean-api
      port: 10006
      protocol: TCP
      targetPort: 10006
  selector:
    zw-nginx-oc: 'true'
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
