apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T06:33:23Z'
  name: zw-ocean-manager
  namespace: zhuowang
  resourceVersion: '4209207'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-ocean-manager
  uid: e1dec1a8-d84b-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.168.193
  ports:
    - name: web1
      port: 11001
      protocol: TCP
      targetPort: 11001
    - name: web
      port: 11007
      protocol: TCP
      targetPort: 11007
  selector:
    zw-ocean-manager: 'true'
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
