apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T06:33:59Z'
  name: zw-ocean-socket
  namespace: zhuowang
  resourceVersion: '4207667'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-ocean-socket
  uid: f747a4ce-d84b-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.107.189
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31037
      port: 11011
      protocol: TCP
      targetPort: 11011
  selector:
    zw-ocean-socket: 'true'
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}