apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T04:43:16Z'
  name: zw-redisp
  namespace: zhuowang
  resourceVersion: '4113632'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-redisp
  uid: 7fa69cc5-d83c-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.88.11
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    zw-redisp: 'true'
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
