apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-09-16T06:38:40Z'
  name: zw-rtmp-server
  namespace: zhuowang
  resourceVersion: '4170549'
  selfLink: /api/v1/namespaces/zhuowang/services/zw-rtmp-server
  uid: 9ede221f-d84c-11e9-bf41-04fe8dbed9ee
spec:
  clusterIP: 172.130.173.152
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32022
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    zw-rtmp-server: 'true'
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
